from .advanced_heuristic import evaluate_advanced_heuristic
from .blocking_heuristic import evaluate_blocking_heuristic
from .distance_heuristic import evaluate_distance_heuristic
from .recursion_heuristic import evaluate_recursion_heuristic